/**
 * Mock Data for Sales Manager Portal
 * In production, this would come from the backend API
 */

import type {
  Company,
  SalesPerson,
  Learner,
  Course,
  DashboardStats,
  ClientActivity,
  Notification,
  CompanyPreset,
  CompanyBranding,
  CompanyFeatures,
} from '@/types';

// Current Sales Person
export const currentSalesPerson: SalesPerson = {
  id: 'sp-001',
  name: 'John Smith',
  email: 'john.smith@koenig-solutions.com',
  avatar: null,
  role: 'sales_manager',
  territory: 'North America',
  companies: ['pwc', 'deloitte', 'acme-tech'],
  totalClients: 12,
  activeClients: 10,
  revenue: 450000,
  target: 500000,
  createdAt: '2023-01-15',
};

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalClients: 45,
  activeClients: 38,
  totalLearners: 2340,
  activeLearners: 1876,
  totalRevenue: 2450000,
  monthlyRevenue: 185000,
  averageCompletionRate: 72,
  averageNPS: 8.4,
  newClientsThisMonth: 3,
  renewalsThisMonth: 5,
};

// Companies
export const companies: Company[] = [
  {
    id: 'pwc-001',
    name: 'PricewaterhouseCoopers',
    slug: 'pwc',
    industry: 'consulting',
    size: 'enterprise',
    logo: '/logos/pwc.png',
    favicon: '/favicons/pwc.ico',
    branding: {
      primaryColor: '#e85d04',
      secondaryColor: '#d00000',
      accentColor: '#ffba08',
      backgroundColor: '#fffcf2',
      headerBackground: '#ffffff',
      textColor: '#2b2d42',
      fontFamily: 'Georgia, serif',
      headingFont: 'Georgia, serif',
      buttonStyle: 'square',
      cardStyle: 'bordered',
      welcomeTitle: 'PwC Learning Academy',
      welcomeSubtitle: 'Building tomorrow\'s leaders through continuous learning',
      loginMessage: 'Sign in with your PwC credentials',
      helpUrl: 'https://pwc.com/support',
      privacyUrl: 'https://pwc.com/privacy',
      termsUrl: 'https://pwc.com/terms',
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: true,
      studyGroups: true,
      forum: true,
      liveSessions: true,
      analytics: true,
      gamification: true,
      flashcards: true,
      mindMaps: true,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: true,
      leaderboards: true,
      customReporting: true,
      apiAccess: true,
    },
    adminEmail: 'learning@pwc.com',
    supportEmail: 'support@pwc.com',
    subscriptionTier: 'enterprise',
    subscriptionStatus: 'active',
    trialEndsAt: null,
    learnerCount: 450,
    activeEnrollments: 1280,
    createdAt: '2024-03-15',
    updatedAt: '2024-12-10',
    createdBy: 'sp-001',
    salesPerson: 'John Smith',
    portalUrl: 'https://pwc.learn.koenig.com',
  },
  {
    id: 'deloitte-001',
    name: 'Deloitte',
    slug: 'deloitte',
    industry: 'consulting',
    size: 'enterprise',
    logo: '/logos/deloitte.png',
    favicon: '/favicons/deloitte.ico',
    branding: {
      primaryColor: '#86bc25',
      secondaryColor: '#0076a8',
      accentColor: '#00a3e0',
      backgroundColor: '#ffffff',
      headerBackground: '#000000',
      textColor: '#333333',
      fontFamily: 'Open Sans, sans-serif',
      headingFont: 'Open Sans, sans-serif',
      buttonStyle: 'rounded',
      cardStyle: 'flat',
      welcomeTitle: 'Deloitte University',
      welcomeSubtitle: 'Learn. Lead. Succeed.',
      loginMessage: 'Sign in with Deloitte SSO',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: true,
      studyGroups: true,
      forum: false,
      liveSessions: true,
      analytics: true,
      gamification: true,
      flashcards: true,
      mindMaps: false,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: false,
      leaderboards: false,
      customReporting: true,
      apiAccess: true,
    },
    adminEmail: 'learning@deloitte.com',
    supportEmail: 'support@deloitte.com',
    subscriptionTier: 'enterprise',
    subscriptionStatus: 'active',
    trialEndsAt: null,
    learnerCount: 320,
    activeEnrollments: 890,
    createdAt: '2024-02-20',
    updatedAt: '2024-12-08',
    createdBy: 'sp-001',
    salesPerson: 'John Smith',
    portalUrl: 'https://deloitte.learn.koenig.com',
  },
  {
    id: 'acme-001',
    name: 'ACME Technologies',
    slug: 'acme-tech',
    industry: 'technology',
    size: 'medium',
    logo: '/logos/acme.png',
    favicon: null,
    branding: {
      primaryColor: '#8b5cf6',
      secondaryColor: '#06b6d4',
      accentColor: '#f43f5e',
      backgroundColor: '#fafaf9',
      headerBackground: '#18181b',
      textColor: '#18181b',
      fontFamily: 'Inter, sans-serif',
      headingFont: 'Inter, sans-serif',
      buttonStyle: 'pill',
      cardStyle: 'elevated',
      welcomeTitle: 'ACME Learning Hub',
      welcomeSubtitle: 'Level up your skills',
      loginMessage: 'Sign in to start learning',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: false,
      studyGroups: true,
      forum: true,
      liveSessions: false,
      analytics: true,
      gamification: true,
      flashcards: true,
      mindMaps: true,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: true,
      leaderboards: true,
      customReporting: false,
      apiAccess: false,
    },
    adminEmail: 'hr@acmetech.com',
    supportEmail: 'support@acmetech.com',
    subscriptionTier: 'professional',
    subscriptionStatus: 'active',
    trialEndsAt: null,
    learnerCount: 85,
    activeEnrollments: 240,
    createdAt: '2024-06-10',
    updatedAt: '2024-12-05',
    createdBy: 'sp-001',
    salesPerson: 'John Smith',
    portalUrl: 'https://acme.learn.koenig.com',
  },
  {
    id: 'healthco-001',
    name: 'HealthCo Medical',
    slug: 'healthco',
    industry: 'healthcare',
    size: 'large',
    logo: null,
    favicon: null,
    branding: {
      primaryColor: '#059669',
      secondaryColor: '#0891b2',
      accentColor: '#6366f1',
      backgroundColor: '#f0fdf4',
      headerBackground: '#ffffff',
      textColor: '#1f2937',
      fontFamily: 'Source Sans Pro, sans-serif',
      headingFont: 'Source Sans Pro, sans-serif',
      buttonStyle: 'rounded',
      cardStyle: 'flat',
      welcomeTitle: 'HealthCo Training Portal',
      welcomeSubtitle: 'Excellence in patient care through education',
      loginMessage: 'Secure sign in required',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: true,
      studyGroups: false,
      forum: false,
      liveSessions: true,
      analytics: true,
      gamification: false,
      flashcards: true,
      mindMaps: false,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: false,
      leaderboards: false,
      customReporting: true,
      apiAccess: false,
    },
    adminEmail: 'training@healthco.com',
    supportEmail: 'support@healthco.com',
    subscriptionTier: 'professional',
    subscriptionStatus: 'trial',
    trialEndsAt: '2025-01-15',
    learnerCount: 120,
    activeEnrollments: 350,
    createdAt: '2024-11-15',
    updatedAt: '2024-12-10',
    createdBy: 'sp-002',
    salesPerson: 'Sarah Johnson',
    portalUrl: 'https://healthco.learn.koenig.com',
  },
];

// Sample Learners
export const learners: Learner[] = [
  {
    id: 'l-001',
    companyId: 'pwc-001',
    name: 'Alice Johnson',
    email: 'alice.johnson@pwc.com',
    department: 'Cloud Engineering',
    enrolledCourses: 3,
    completedCourses: 2,
    progress: 78,
    lastActive: '2024-12-10T10:30:00Z',
    status: 'active',
  },
  {
    id: 'l-002',
    companyId: 'pwc-001',
    name: 'Bob Williams',
    email: 'bob.williams@pwc.com',
    department: 'DevOps',
    enrolledCourses: 2,
    completedCourses: 1,
    progress: 45,
    lastActive: '2024-12-09T14:20:00Z',
    status: 'active',
  },
  {
    id: 'l-003',
    companyId: 'deloitte-001',
    name: 'Carol Davis',
    email: 'carol.davis@deloitte.com',
    department: 'IT Infrastructure',
    enrolledCourses: 4,
    completedCourses: 3,
    progress: 92,
    lastActive: '2024-12-10T09:15:00Z',
    status: 'active',
  },
];

// Available Courses
export const courses: Course[] = [
  {
    id: 'az-104',
    code: 'AZ-104',
    name: 'Microsoft Azure Administrator',
    vendor: 'Microsoft',
    category: 'Cloud',
    level: 'intermediate',
    duration: 40,
    enrollments: 1250,
    completionRate: 76,
    rating: 4.8,
    price: 2500,
    isActive: true,
  },
  {
    id: 'az-400',
    code: 'AZ-400',
    name: 'Microsoft Azure DevOps Engineer',
    vendor: 'Microsoft',
    category: 'DevOps',
    level: 'advanced',
    duration: 48,
    enrollments: 890,
    completionRate: 68,
    rating: 4.7,
    price: 3000,
    isActive: true,
  },
  {
    id: 'aws-saa',
    code: 'SAA-C03',
    name: 'AWS Solutions Architect Associate',
    vendor: 'AWS',
    category: 'Cloud',
    level: 'intermediate',
    duration: 45,
    enrollments: 980,
    completionRate: 71,
    rating: 4.6,
    price: 2800,
    isActive: true,
  },
  {
    id: 'cka',
    code: 'CKA',
    name: 'Certified Kubernetes Administrator',
    vendor: 'CNCF',
    category: 'DevOps',
    level: 'advanced',
    duration: 35,
    enrollments: 650,
    completionRate: 62,
    rating: 4.5,
    price: 2200,
    isActive: true,
  },
];

// Recent Activity
export const recentActivity: ClientActivity[] = [
  {
    id: 'a-001',
    companyId: 'pwc-001',
    companyName: 'PricewaterhouseCoopers',
    type: 'completion',
    description: '15 learners completed AZ-104 certification',
    timestamp: '2024-12-10T11:30:00Z',
  },
  {
    id: 'a-002',
    companyId: 'deloitte-001',
    companyName: 'Deloitte',
    type: 'enrollment',
    description: 'Enrolled 25 new learners in AWS track',
    timestamp: '2024-12-10T09:15:00Z',
  },
  {
    id: 'a-003',
    companyId: 'healthco-001',
    companyName: 'HealthCo Medical',
    type: 'signup',
    description: 'New client signed up for trial',
    timestamp: '2024-12-09T16:45:00Z',
  },
  {
    id: 'a-004',
    companyId: 'acme-001',
    companyName: 'ACME Technologies',
    type: 'renewal',
    description: 'Subscription renewed for 12 months',
    timestamp: '2024-12-08T10:00:00Z',
  },
  {
    id: 'a-005',
    companyId: 'pwc-001',
    companyName: 'PricewaterhouseCoopers',
    type: 'payment',
    description: 'Invoice #INV-2024-1234 paid ($45,000)',
    timestamp: '2024-12-07T14:30:00Z',
  },
];

// Notifications
export const notifications: Notification[] = [
  {
    id: 'n-001',
    type: 'success',
    title: 'New Client Signed',
    message: 'HealthCo Medical has started their trial period',
    timestamp: '2024-12-10T10:00:00Z',
    isRead: false,
    actionUrl: '/clients/healthco-001',
  },
  {
    id: 'n-002',
    type: 'warning',
    title: 'Trial Expiring Soon',
    message: 'HealthCo Medical trial expires in 35 days',
    timestamp: '2024-12-10T09:00:00Z',
    isRead: false,
    actionUrl: '/clients/healthco-001',
  },
  {
    id: 'n-003',
    type: 'info',
    title: 'Monthly Report Ready',
    message: 'November 2024 analytics report is available',
    timestamp: '2024-12-01T08:00:00Z',
    isRead: true,
    actionUrl: '/reports',
  },
];

// Company Presets
export const companyPresets: CompanyPreset[] = [
  {
    id: 'consulting',
    name: 'Consulting (Big 4)',
    description: 'Professional, enterprise-focused design',
    industry: 'consulting',
    branding: {
      primaryColor: '#1e3a5f',
      secondaryColor: '#2563eb',
      accentColor: '#fbbf24',
      backgroundColor: '#f8fafc',
      headerBackground: '#1e3a5f',
      textColor: '#1e293b',
      fontFamily: 'Inter, sans-serif',
      headingFont: 'Inter, sans-serif',
      buttonStyle: 'square',
      cardStyle: 'bordered',
      welcomeTitle: 'Learning Academy',
      welcomeSubtitle: 'Professional development for excellence',
      loginMessage: 'Sign in with your corporate credentials',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: true,
      studyGroups: true,
      forum: true,
      liveSessions: true,
      analytics: true,
      gamification: true,
      flashcards: true,
      mindMaps: true,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: true,
      leaderboards: true,
      customReporting: true,
      apiAccess: true,
    },
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    description: 'Modern, playful design for tech companies',
    industry: 'technology',
    branding: {
      primaryColor: '#8b5cf6',
      secondaryColor: '#06b6d4',
      accentColor: '#f43f5e',
      backgroundColor: '#fafaf9',
      headerBackground: '#18181b',
      textColor: '#18181b',
      fontFamily: 'Inter, sans-serif',
      headingFont: 'Inter, sans-serif',
      buttonStyle: 'pill',
      cardStyle: 'elevated',
      welcomeTitle: 'Level Up Your Skills',
      welcomeSubtitle: 'Learn fast. Build faster.',
      loginMessage: 'Let\'s get learning!',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: false,
      studyGroups: true,
      forum: true,
      liveSessions: false,
      analytics: true,
      gamification: true,
      flashcards: true,
      mindMaps: true,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: true,
      leaderboards: true,
      customReporting: false,
      apiAccess: false,
    },
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Clean, professional design for medical organizations',
    industry: 'healthcare',
    branding: {
      primaryColor: '#059669',
      secondaryColor: '#0891b2',
      accentColor: '#6366f1',
      backgroundColor: '#f0fdf4',
      headerBackground: '#ffffff',
      textColor: '#1f2937',
      fontFamily: 'Source Sans Pro, sans-serif',
      headingFont: 'Source Sans Pro, sans-serif',
      buttonStyle: 'rounded',
      cardStyle: 'flat',
      welcomeTitle: 'Healthcare Training Portal',
      welcomeSubtitle: 'Excellence through education',
      loginMessage: 'Secure sign in required',
      helpUrl: null,
      privacyUrl: null,
      termsUrl: null,
    },
    features: {
      courseContent: true,
      quizzes: true,
      qubits: true,
      certificates: true,
      aiAssistant: true,
      studyGroups: false,
      forum: false,
      liveSessions: true,
      analytics: true,
      gamification: false,
      flashcards: true,
      mindMaps: false,
      focusMode: true,
      calendar: true,
      examSimulator: true,
      weakAreaDrills: true,
      progressSharing: false,
      leaderboards: false,
      customReporting: true,
      apiAccess: false,
    },
  },
];

// Helper to generate portal URL
export function generatePortalUrl(slug: string): string {
  return `https://${slug}.learn.koenig.com`;
}

// Helper to generate login credentials
export function generateCredentials(companySlug: string): { url: string; adminEmail: string; tempPassword: string } {
  return {
    url: generatePortalUrl(companySlug),
    adminEmail: `admin@${companySlug}.com`,
    tempPassword: `Welcome${companySlug.charAt(0).toUpperCase()}${companySlug.slice(1)}2024!`,
  };
}
